//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vlko.core {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ModelResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ModelResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("vlko.core.ModelResources", typeof(ModelResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow comments.
        /// </summary>
        public static string AllowComments {
            get {
                return ResourceManager.GetString("AllowComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changed.
        /// </summary>
        public static string Changed {
            get {
                return ResourceManager.GetString("Changed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last change date.
        /// </summary>
        public static string ChangeDate {
            get {
                return ResourceManager.GetString("ChangeDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ip of client.
        /// </summary>
        public static string ClientIp {
            get {
                return ResourceManager.GetString("ClientIp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of comments.
        /// </summary>
        public static string CommentCounts {
            get {
                return ResourceManager.GetString("CommentCounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of creation.
        /// </summary>
        public static string CreatedDate {
            get {
                return ResourceManager.GetString("CreatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creator.
        /// </summary>
        public static string Creator {
            get {
                return ResourceManager.GetString("Creator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File deletion failed..
        /// </summary>
        public static string FileDeleteFailedError {
            get {
                return ResourceManager.GetString("FileDeleteFailedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New file name.
        /// </summary>
        public static string FileIdent {
            get {
                return ResourceManager.GetString("FileIdent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File ident &apos;{0}&apos; already used..
        /// </summary>
        public static string FileIdentExistsError {
            get {
                return ResourceManager.GetString("FileIdentExistsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File ident (without extension) required..
        /// </summary>
        public static string FileIdentRequireError {
            get {
                return ResourceManager.GetString("FileIdentRequireError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File too big (max size {0})..
        /// </summary>
        public static string FileTooBigError {
            get {
                return ResourceManager.GetString("FileTooBigError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File upload failed..
        /// </summary>
        public static string FileUploadFailedError {
            get {
                return ResourceManager.GetString("FileUploadFailedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friendly URL.
        /// </summary>
        public static string FriendlyUrl {
            get {
                return ResourceManager.GetString("FriendlyUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friendly URL longer like 80 characters..
        /// </summary>
        public static string FriendlyURLError {
            get {
                return ResourceManager.GetString("FriendlyURLError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ident.
        /// </summary>
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item not exists..
        /// </summary>
        public static string ItemNotExistsError {
            get {
                return ResourceManager.GetString("ItemNotExistsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not allowed to change this item..
        /// </summary>
        public static string NotAllowedToChangeError {
            get {
                return ResourceManager.GetString("NotAllowedToChangeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not allowed to delete this item..
        /// </summary>
        public static string NotAllowedToDeleteError {
            get {
                return ResourceManager.GetString("NotAllowedToDeleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish date.
        /// </summary>
        public static string PublishDate {
            get {
                return ResourceManager.GetString("PublishDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish date empty..
        /// </summary>
        public static string PublishDateRequireError {
            get {
                return ResourceManager.GetString("PublishDateRequireError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File size.
        /// </summary>
        public static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string Text {
            get {
                return ResourceManager.GetString("Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text empty..
        /// </summary>
        public static string TextRequireError {
            get {
                return ResourceManager.GetString("TextRequireError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title longer like 80 characters..
        /// </summary>
        public static string TitleLengthError {
            get {
                return ResourceManager.GetString("TitleLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title empty..
        /// </summary>
        public static string TitleRequireError {
            get {
                return ResourceManager.GetString("TitleRequireError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url path.
        /// </summary>
        public static string Url {
            get {
                return ResourceManager.GetString("Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of user.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
    }
}
